# LAB 01 - NumPy Library [1]

## #01. NumPy 시작하기

### 라이브러리 참조하기

In [ ]:
# 라이브러리 설치:
    # pip install --upgrade numpy

# numpy 라이브러리를 np라는 이름으로 사용하도록 import:
import numpy as np

### 배열 생성하기
###### 리스트를 통한 1차원(=1행 구성) 배열 만들기

In [ ]:
# list를 파라미터로 전달하여 ndarray 객체 생성:
arr = np.array([1, 3, 5, 7, 9])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

### 배열의 크기
###### 'len()' 함수를 사용하여 배열의 크기를 확인할 수 있다.

In [9]:
arr = np.array([10, 30, 50, 70, 90])
size = len(arr)
print("배열의 원소는 %d개 입니다." % size)

배열의 원소는 5개 입니다.


### 배열의 인덱싱과 슬라이싱
###### 기본 특성이 리스트와 동일 -> 인덱싱과 슬라이싱 가능

In [11]:
mydata = np.array([5, 10, 15, 20, 25])

# 인덱싱을 사용한 원소의 접근
print(mydata[0])
print(mydata[1])
print(mydata[3])

# 슬라이싱을 사용한 구간 추출
print(mydata[1:4])
print(mydata[-4:-1])

5
10
20
[10 15 20]
[10 15 20]


### 반복문을 통한 활용
###### 리스트랑 동일하게 사용 가능

In [14]:
mydata = np.array([100, 110, 120, 130, 140])

for i, v in enumerate(mydata):
    print("%d번째 원소: %d" % (i, v))

0번째 원소: 100
1번째 원소: 110
2번째 원소: 120
3번째 원소: 130
4번째 원소: 140


### ndarray의 특성

In [17]:
# list의 경우: 서로 다른 데이터 타입의 원소를 허용함
mylist = [100, 3.14, True]
mylist

# ndarray의 경우: 가장 포괄적인 데이터 타입으로 다 동일시킴
    # 서로 다른 원소 타입을 허용 안하기 때문
    # 여기선 실수 범위가 더 큼 (True: 0 or 1) 
        # 모든 원소를 실수형으러 변환
myarr = np.array(mylist)
myarr

array([100.  ,   3.14,   1.  ])