# LAB 01 - NumPy Library [1]
## #02. ndarray의 주요 기능

### 라이브러리 참조하기

In [3]:
# numpy 라이브러리를 np라는 이름으로 사용하도록 import 해오기:
import numpy as np

### 타입 지정
###### dtype 파라미터를 사용한 강제 타입 지정

In [10]:
# ndarray를 생성하는 과정에서 np.array() 메서드에 
    # dtype 파라미터로 특정 타입을 강제 지정할 수 있다.
    # dtype = data type (int, float, str, bool)

# ex) 실수형 값 -> 정수로 변환: 소수점 아래는 모두 '버림'
mylist1 = [100.12, 3.14, 1.5]
myarr1 = np.array(mylist1, dtype = 'int')
myarr1

array([100,   3,   1])

### 문자열이 포함된 경우의 형 변환
###### 모든 프로그래밍 언어에선 문자열은 표현범위가 가장 넓은 타입임

In [11]:
# 문자열이 포함된 리스트를 ndarray로 변환할 경우:
    # 모든 원소의 타입은 문자열이 된다!
mylist2 = [1, 2, 3, True, '4']
myarr2 = np.array(mylist2)
myarr2                      # <U21, <U32: str을 뜻함

array(['1', '2', '3', 'True', '4'], dtype='<U21')

### list 타입으로 '역'변환
###### ndarray랑 list는 서로 호환 가능

In [30]:
mylist3 = [10, 20, 30, 40, 50]
# list -> ndarrat: np.array(list)
myarr3 = np.array(mylist3)
print(type(myarr3), myarr3)

# nddarray -> list: list(array)
mylist3_1 = list(myarr3)
print(type(mylist3_1), mylist3_1)
# int64(n): 64비트의 정수 n (그냥 정수 n을 뜻함)

<class 'numpy.ndarray'> [10 20 30 40 50]
<class 'list'> [np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


### 연산자를 사용한 ndarray 연산
###### 위치가 동일한 원소끼리의 연산을 수행한다

In [20]:
# ndarray 생성
arr1 = np.array([10, 15, 20, 25, 30])
arr2 = np.array([2, 3, 4, 5, 6])

In [21]:
# 같은 위치 원소 덧셈
a = arr1 + arr2
a

array([12, 18, 24, 30, 36])

In [22]:
# 같은 위치 원소 뺄셈
b = arr1 - arr2
b

array([ 8, 12, 16, 20, 24])

In [23]:
# 같은 위치 원소 곱셈
c = arr1 * arr2
c

array([ 20,  45,  80, 125, 180])

In [24]:
# 같은 위치 원소 나눗셈
d = arr1 / arr2
d

array([5., 5., 5., 5., 5.])

### Numpy의 함수를 사용한 연산
###### 연산자를 사용한 경우랑 동일한 결과를 얻는다
###### 함수보다는 연산자가 더 쓰기 편함 (별칭 사용 했을 때)

In [26]:
# 같은 위치 원소 덧셈
a = np.add(arr1, arr2)
a

array([12, 18, 24, 30, 36])

In [27]:
# 같은 위치 원소 뺄셈
b = np.subtract(arr1, arr2)
b

array([ 8, 12, 16, 20, 24])

In [28]:
# 같은 위치 원소 곱셈
c = np.multiply(arr1, arr2)
c

array([ 20,  45,  80, 125, 180])

In [29]:
# 같은 위치 원소 나눗셈
d = np.divide(arr1, arr2)
d

array([5., 5., 5., 5., 5.])

### 조건에 맞는 위치의 원소 추출
###### 나중에 Pandas에서 자주 쓸거임!

In [36]:
# 철수의 1 ~ 4학년 동안의 평균 점수:
grade = np.array([82, 77, 91, 88])
grade

array([82, 77, 91, 88])

In [37]:
# -> 추출하고자 하는 원본과 '같은 사이즈의 배열'을 생성한다
# -> 추출할 값: True, 제외할 값: False 지정:
bool_array = np.array([True, False, True, False])
bool_array

array([ True, False,  True, False])

In [38]:
# -> 조건에 맞는 항목만 1차 배열로 추출:
result1 = grade[bool_array]
result1

array([82, 91])

### 조건식에 따른 원소 추출
###### np.where(a, b, c)랑 np.select(a, b, c) 개큰중요!

In [ ]:
# 80점 이상의 원소만 추출하기:
# -> 조건을 명시하기 위해 배열의 이름이 조건식에 명시되어야 함
mypoint = np.array([82, 77, 91, 88])
ge80 = mypoint[mypoint >= 80]
ge80

In [44]:
mypoint = np.array([82, 77, 91, 88])

# np.logical_and
ge80ge90 = mypoint[np.logical_and(mypoint >= 80, mypoint <= 90)]
ge80ge90

array([82, 88])

In [45]:
mypoint = np.array([82, 77, 91, 88])

# np.logical_or
gt_or_lt = mypoint[np.logical_or(mypoint < 80, mypoint > 90)]
gt_or_lt

array([77, 91])

### NumPy의 조건연산
###### SQL의 IF() 힘수랑 결과가 동일함

In [ ]:
exam = np.array([60, 83, 75, 92, 86])

# np.where(a, b, c) -> 이거 큰중요, 강조하심
    # a: 주어진 조건(범위)
    # b: a가 참일 경우의 출력값
    # c: a가 거짓일 경우의 출력값
result = np.where(exam >= 80, "합격", "불합격")
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

### 짝홀 코딩법 1

In [5]:
a = 100
b = None

if a % 2 == 0:
    b = "짝수"
else:
    b = "홀수"
print(b)

짝수


### 짝홀 코딩법 2

In [3]:
a = 100
b = "짝수" if a % 2 == 0 else "홀수"
print(b)

짝수


### 여러 조건들을 한번에 처리하는 방법:

In [52]:
exam = np.array([60, 85, 51, 94, 88])

# 학점 부여를 위한 점수구간들을 설정하는 조건들을 리스트로 만들고:
conditions = [
    (exam >= 90),   # if
    (exam >= 80),   # elif
    (exam >= 70)    # elif
]

# 조건에 따라 부여될 학점도 리스트로 만들기:
value = ['A', 'B', 'C']

# 조과 조건을 판단하기 위한 값 지정 방법:
    # np.select(a, b, c) -> 얘도 개큰중요
        # a: 조건 리스트
        # b: 값 리스트
        # c: 디폴트 값
    # default: 조건들에 다 맞지않는 값을 위해 지정 (생략 가능)
result = np.select(conditions, value, default = 'F')
result

# 출력결과: 파생변수로 나타남
    # 데이터 전처리의 기반임!!!
    # in 데이터분석: column = 변수

array(['F', 'B', 'F', 'A', 'B'], dtype='<U1')