# LAB 01- NumPy Library [1]

## #03. 그 밖의 ndarray 형태

### 라이브러리 참조하기

In [1]:
import numpy as np

### 2차원 배열
###### 2차원 리스트를 ndarray로 변환:

In [2]:
# 배열의 정보를 확인할 수 있는 프로퍼티가 포함됨
myarray = np.array(
    [
        [98, 72, 80, 64], 
        [88, 90, 80, 72], 
        [92, 88, 82, 76] 
    ]
)

print(myarray)

print("차원 크기:", myarray.ndim)   # .ndim: 몇차원?
print("차원 별 원소 수:", myarray.shape) # .shape: (a, b):a행 b열
print("원소의 데이터 타입:", myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원 크기: 2
차원 별 원소 수: (3, 4)
원소의 데이터 타입: int64


### boolean 타입으로 인덱싱 하는 법:
###### 조건에 맞는 원소를 '1차원 배열'로 변환함

In [3]:
bool_array = (
    [
        [True, False, True, False], 
        [True, True, True, False], 
        [True, True, True, False]
    ]
)

# 조건에 맞는 항목만 1차원 배열로 추출
# myarray는 이전 실습 때 생성한 2차원 배열임
result1 = myarray[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

### 비교식에 의한 검색
###### 얘도 결과는 무조건 1차원으로 떨어진다!!

In [5]:
result2 = myarray[myarray >= 80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

In [6]:
# AND 검색
result3 = myarray[np.logical_and(myarray >= 80, myarray <= 90)]
result3

array([80, 88, 90, 80, 88, 82])

In [7]:
# OR 검색
result4 = myarray[np.logical_or(myarray < 80, myarray > 90)]
result4

array([98, 72, 64, 72, 92, 76])

### 정형화 된 배열 생성

In [14]:
# 모든 원소가 0인 배열:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# 모든 원소가 1인 배열:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# 모든 원소가 특정 값인 배열:
np.full([3,4], 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [18]:
# 단위 행렬_대각선 원소는 1, 그 외에는 0인 배열:
np.eye(4)   # np.eye([4,4])는 에러 뜸!

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 랜덤 배열
###### 딥러닝 들어갈 때 개~~중요!!!!!!

In [19]:
# 파라미터가 한개(a)만 주어진 경우: 1행 n열로 간주
# -> 0부터 1의 범위에서 균등하게 추출하여 N차원 랜덤 배열 생성

# ex) 10개 값, 1차원 배열:
np.random.rand(10)

array([0.2264886 , 0.21825093, 0.13037874, 0.72291633, 0.18677513,
       0.79218775, 0.89210356, 0.1202276 , 0.45111297, 0.68531053])

In [20]:
# 파라미터가 2개(a, b) 주어진 경우: a행 b열

# ex) 4행 3열인 2차원 랜덤배열 생성:
np.random.rand(4, 3)

array([[0.95638133, 0.49983063, 0.33742793],
       [0.27728579, 0.59339306, 0.04017841],
       [0.75551853, 0.01088862, 0.74419023],
       [0.70001456, 0.54134872, 0.41505045]])

### 파라미터가 3개 주어진 경우: 
###### (a, b, c): a에서 b 사이의 랜덤값 c개를 1차원 배열로 생성
###### (a, b, (c,d)): a에서 b 사이의 랜덤값들을 c행 d열로 생성

In [24]:
# 0부터 9 사이의 랜덤 정수 10개를 1차원 배열로 나타낼 때:
np.random.randint(0, 9, 10)     # randint: 랜덤정수


array([1, 2, 4, 1, 0, 8, 4, 7, 2, 0], dtype=int32)

In [25]:
# 0부터 9 사이의 랜덤 정수를 3행 4열의 2차원 배열로 나타낼 때:
np.random.randint(0, 9, (3,4))

array([[0, 5, 6, 0],
       [7, 0, 0, 2],
       [3, 4, 8, 0]], dtype=int32)

### 랜덤 시드 고정
###### Random Seed: 겉보기에 무작위지만, 실제로는 컴터가 특정 규칙(알고리즘)에 따라 만들어내는 가짜 무작위 값인 난수를 표현할 때
###### 그 표현 규칙을 어디서부터 시작할 지 정하는 '출발점 값'임!
###### -> 같은 시드를 주면: 항상 같은 난수 결과가 나옴
###### -> 다른 시드를 주면: 완전 다른 난수 결과가 나옴

In [28]:
np.random.seed(1234)

In [ ]:
# np.random.normal(μ, σ, (a, b)): 
    # μ: 평균 / σ: 표준편차 / (a, b): a행 b열
np.random.normal(0, 1, (4, 3))
    # normal 이외의 모든 랜덤함수는 다 같음

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

### 표준 정규분포를 따르는 랜덤배열

In [31]:
# 원소가 10개인 1차원 배열:
np.random.randn(10)  # randn의 n은 표준화(normalization)을 뜻한

array([ 0.95332413, -2.02125482, -0.33407737,  0.00211836,  0.40545341,
        0.28909194,  1.32115819, -1.54690555, -0.20264632, -0.65596934])

In [32]:
# 4행 3열의 2차원 배열:
np.random.randn(4, 3)

array([[ 0.19342138,  0.55343891,  1.31815155],
       [-0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023],
       [ 0.33743765,  1.04757857,  1.04593826]])