# LAB 01- NumPy Library [1]

## #04. ndarray의 변환:
###### 형변환 (데이터타입), 차원변환 (n차원)

### 라이브러리 참조하기

In [2]:
import numpy as np

### 원소의 데이터 타입 변환[1] - .astype() 함수 사용:
##### '바꿀배열.astype('float'|'str')'

In [21]:
# 1. 실습을 위한 원본 배열 구성
# -> 0부터 '10 전까지' 1씩 증가하는 원소를 가지는 배열 만들기:
arr1 = np.arange(10) #.arange(n): 0부터 n 전까지 1씩 증가하는 배열
print("원본 배열:", arr1)
print("원본 배열의 데이터 타입:", arr1.dtype)

원본 배열: [0 1 2 3 4 5 6 7 8 9]
원본 배열의 데이터 타입: int64


In [12]:
# 2. 실수(float) 타입으로 변환해보기:
arr2 = arr1.astype('float')
print("항변환 후 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

항변환 후 배열: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입: float64


In [14]:
# 3. 문자열(str) 타입으로 변환해보기:
arr3 = arr1.astype('str')
print("항변환 후 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

항변환 후 배열: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
변환된 배열의 데이터 타입: <U21


### 원소의 데이터 타입 변환[2] - .asarray() 함수 사용:
##### np.asarray(바꿀배열, dtype='float'|'str')

In [22]:
# 1. 원본 배열 구성
# -> 10 부터 20 전 까지 1씩 증가하는 원소를 가지는 배열 만들기:
arr1 = np.arange(10, 20) # 시작점 원하면 .arange(시작, 끝전) ㄱㄱ
print("원본 배열:", arr1)
print("원본 배열의 데이터 타입:", arr1.dtype)

원본 배열: [10 11 12 13 14 15 16 17 18 19]
원본 배열의 데이터 타입: int64


In [24]:
# 2. 실수 타입으로 변환:
arr2 = np.asarray(arr1, dtype='float')
print("형변환 후 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후 배열: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
변환된 배열의 데이터 타입: float64


In [27]:
# 3. 문자열 타입으로 변환:
arr3 = np.asarray(arr1, dtype='str')
print("형변환 후 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후 배열: ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
변환된 배열의 데이터 타입: <U21


### 차원 변환
##### reshape(행, 열) 함수 사용

In [37]:
# 1. 1부터 20 전 까지 1씩 증가하는 1차원 배열 생성:
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
# 2. 1차원 배열을 4행 5열의 2차원 배열로 변환:
x = origin.reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
# 3. 변환 불가능한 case:
origin.reshape(3, 7)

ValueError: cannot reshape array of size 20 into shape (3,7)

### 차원 축소
##### reshape() 함수 사용

In [42]:
# 1. 원본 배열 구성:
origin = np.array(
    [
        [0, 1, 2, 3, 4], 
        [5, 6, 7, 8, 9], 
        [10, 11, 12, 13, 14], 
        [15, 16, 17, 18, 19]
    ]
)
origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
# 2. 1차원 배열로 축소해보기:
# -> .reshape() 함수 안에 파라미터를 1개만 넣으면 1차 n열 로 됨
y = origin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
# 3. 원소 갯수 계산 후 1차원 배열로 축소해보기:
# -> 일일이 원소 수 카운트 귄찮 -> .shape 함수 이용해보자
rows, cols = origin.shape
rows, cols

(4, 5)

In [45]:
z = origin.reshape(rows * cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### reshpae() 함수에서 -1의 의미: 
### ((-1, 1), (1, -1)) -> 2차원, (-1) -> 1차원 외우기
###### 변경 후 배열의 '-1' 위치의 차원은 '원래 배열의 길이와 남은 차원으로 부터 추정'이 된다는 뜻

In [49]:
# 행 자리에 -1 오는 경우: reshape(-1, n)

# 1. 원본 배열 생성
origin = np.array(
    [
        [0, 1, 2, 3], 
        [4, 5, 6, 7], 
        [8, 9, 10, 11] 
    ]
)
origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 2. reshape(-1, n): 
# '행의 수에 관계 없이' '열 1개'를 가지는 행렬로 재 구성
# -> 2차원으로 나옴!! 
x = origin.reshape(-1, 1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [52]:
# 3. '행 수에 관계없이' '2열'인 2차원 배열로 재 구성:
y = origin.reshape(-1, 2)
y
# (원소가 홀수개면 에러뜰거임)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [53]:
# 열 자리에 -1 오는 경우: reshape(n, -1)

# 1. 원본 배열 생성
origin = np.arange(12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
# 2. reshape(n, -1): 
# '열의 수에 관계 없이' 행 1개를 가지는 행렬로 재 구성
# -> 2차원으로 나옴!! 
x = origin.reshape(1, -1)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [55]:
# 3. '열 수에 관계없이' 2행인 2차원 배열로 재 구성:
y = origin.reshape(2, -1)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [56]:
# reshape(-1)인 경우:
    # 걍 1차원으로 바꾸라는 뜻. 행 수에 상관 없이

# 1. 원본:
origin = np.array(
    [
        [0, 1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10, 11]
    ]
)
print(origin)

# 2. 1차로 재배치:
x = origin.reshape(-1)
x

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# functions with regard to normal distributions:

    # np.random.rand(): 균등 분포
    # np.random.randn(): 정규 분포
    # np.random.normal(): 표준 정규 분포

