# LAB 01- NumPy Library [1]

## #05. 기초 통계량의 이해 (1)
###### = EDA (Exploratory Data Analysis)

In [8]:
# 기초통계는 EDA(Exploratory Data Analysis) 기반임:
    # -> 예측이 들어가지 않음
        # 과거랑 (~현재)에 대한 이유 밝히는거임

# 중앖값 = 중위값(median, mϵ)
    # 순서 상 중앙에 있는 값
    # 극단값(=극단치=이상치, outlier)에 영향 거의 안받음
    # 평균 ≒ 중앙값 -> 정규분포를 따른다고 여김
    # if 총 도수가 짝수면: 중앙값은 실제값 아님, 계산값임

# 사분위수: for 데이터 분포 형태
    # 데이터를 4등분 하는 기준값
    # 25%, 50%, 75% 지점의 수치를 '계산한 값!
        # Q1(25%), Q2(50%), Q3(75%)로 표현
    # 소수점 내림:└┘/ 소수점 올림: ┏┓

# 편차: 관측값 - 평균값
    # 분산: 편차들의 제곱의 평균 (표준편차의 제곱)
        # 표준편차: 분산의 제곱근

# axis=0: 같은 열번호의 원소들끼리 계산 (세로연산)
# axis=1: 각 행 안의 원소들끼리 계산 (가로연산)

### 라이브러리 참조

In [1]:
import numpy as np

### 샘플 데이터 생성

In [3]:
myarr = np.array(
    [98, 72, 80, 64, 88, 65,79 , 59, 81, 74]
)
myarr

array([98, 72, 80, 64, 88, 65, 79, 59, 81, 74])

### 데이터 위치, 분포를 나타내는 기초 통계량

In [5]:
# 총 도수
print("총 도수:", len(myarr))

총 도수: 10


In [6]:
# 최대(max), 최소(min), 합계(∑)
print("최댓값:", np.max(myarr))
print("최솟값:", np.min(myarr))
print("합계:", np.sum(myarr))

최댓값: 98
최솟값: 59
합계: 760


In [7]:
# 평균(μ)
print("평균:", np.average(myarr))

평균: 76.0


### 중앙값 (방법 두 가지)

In [ ]:
# 중앙값: 모든 값을 순서대로 정렬 후 가운데 위치의 값
    # 극단치(outlier)의 영향을 안받음 
        # -> 평균 or 표준편차보다 
        # outlier가 많은 데이터의 중심 위치, 범위에 너 나은 측도

#------------------------------------------------------------
# 방법 1. 직접 구하기
size = len(myarr)           # 전체 데이터 수
sorted_arr = np.sort(myarr) # 순서대로 정렬
print("정렬:", sorted_arr)

# 짝수인 경우: 가운데 두 수의 평균 내기:
if size % 2 == 0:
    p = (size // 2) - 1
    q = p + 1
    median = (sorted_arr[p] + sorted_arr[q]) / 2
else:
    p = size // 2
    median = sorted_arr[p]

print("중앙값:", median)
#------------------------------------------------------------

정렬: [59 64 65 72 74 79 80 81 88 98]
중앙값: 76.5


In [ ]:
# 방법 2. NumPy API 사용해서 구하기
print("중앙값:", np.median(myarr))
#------------------------------------------------------------

중앙값: 76.5


### 사분위 수

In [ ]:
# 사분위 수: 데이터를 순서대로 정렬 후 
    # 25%, 50%, 75% 위치 지점의 수치를 계산한 값
    # 데이터 집합의 범위, 중심 위치 판단에 활용
    # 데이터를 이해하는 데 중요한 첫 번째 단계이다!
#------------------------------------------------------------
# 1사분위 수
x = np.sort(myarr)          # 데이터 정렬 (if n=10일 때:)
n = len(x)                  # 총 도수 (n=10)
q1_pos = (n - 1) * 0.25     # 위치 계산(p) (q1_pos = 2.25 -> 25% 지점은 2랑 3 사이에 있음을 뜻함!)
i = int(np.floor(q1_pos))   # 아래쪽 인덱스(i) (아래인덱스, i = 2)
f = q1_pos - i              # 보간비율(f) (f = 2.25 - 2 = 0.25)

# 보간 (interpolation):
Q1 = x[i] + f * (x[i + 1] - x[i])
print("직접 계산한 1사분위 수:", Q1)

# numpy 내장 함수랑 비교:
print("NumPy로 계산한 1사분위 수:", np.quantile(myarr, 0.25))

#------------------------------------------------------------

직접 계산한 1사분위 수: 66.75
NumPy로 계산한 1사분위 수: 66.75


In [ ]:
#------------------------------------------------------------
# 3사분위 수
x = np.sort(myarr)      # 데이터 정렬 (똑같이 if n=10일 떄:)
n = len(myarr)          # 총 도수
q3_pos = (n - 1) * 0.75 # 위치 계산(p) (q3_pos = 7.75 -> 75% 지점은 7과 8 사이에 있음을 의미)
i = int(np.floor(q3_pos)) # 아래쪽 인덱스(i) (i = 7)
f = q3_pos - i          # 보간비율(f) (f = 7.75 - 7 = 0.75)

# 보간(interpolation)
Q3 = x[i] + f * (x[i + 1] - x[i])
print("직접 계산한 1사분위 수:", Q3)

# numpy
print("NumPy로 계산한 3사분위 수:", np.quantile(myarr, 0.75))

#------------------------------------------------------------

직접 계산한 1사분위 수: 80.75
NumPy로 계산한 3사분위 수: 80.75


### 데이터의 범위, 산포도를 나타내는 기초 통계량

In [ ]:
# 데이터 구간 (Range)
    # 의미: 최댓값 - 최솟값
    # 해석: 전체 변동 폭
print("데이터 구간:", np.max(myarr) - np.min(myarr))

데이터 구간: 39


In [ ]:
# 사분위 수 구간 (IQR)
    # 의미: Q3 - Q1 
    # 해석:중앙 50% 분포 폭, 이상치 판단
print("사분위 수 구간 (IQR):", np.quantile(myarr, 0.75) - np.quantile(myarr, 0.25))


사분위 수 구간 (IQR): 14.0


In [ ]:
# 분산
    # 의미: 편차 제곱의 평균
    # 해석: 변동성 크기
print("분산:", np.var(myarr))

# 표준편차
    # 의미: 분산의 제곱근
    # 해석: 평균으로부터의 거리, 안정성 척도
print("표준편차:", np.std(myarr))

분산: 125.2
표준편차: 11.189280584559492


In [ ]:
# 세로연산: 각 열끼리 연산 -> axis = 0
mydata = np.array(
    [
        [98, 72, 80, 64, 88],
        [65, 79, 59, 81, 74]
    ]
)

s1 = np.sum(mydata, axis = 0)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([163, 151, 139, 145, 162])

In [ ]:
# 가로연산: 각 행끼리 연산 -> axis = 1
mydata = np.array(
    [
        [98, 72, 80, 64, 88],
        [65, 79, 59, 81, 74]
    ]
)

s2 = np.sum(mydata, axis = 1)
print(type(s2))
s2

<class 'numpy.ndarray'>


array([402, 358])