### 01. NumPy 시작하기

In [39]:
# numpy 라이브러리 import 해오기:
import numpy

#---------------------------------------
# 주어진 정수들로 배열(ndarray) 만들기:
arr = numpy.array([10, 20, 30, 40, 50])
print("array =", arr)

#---------------------------------------
# 배열의 길이(원소 갯수) 출력하기:
print("배열의 원소의 갯수:", len(arr))

#---------------------------------------
# 배열의 첫 번째 원소랑 마지막 두개 원소 각각 출력하기:
print("첫 번째 원소:", arr[0])
print("마지막 두개 원소:", arr[-2:])

#---------------------------------------
# for문과 enumerate()를 이용해서 인덱스랑 값을 함께 출력하기:
for i, v in enumerate(arr):
    print("%d 번째 원소: %d" % (i, v))

#tpl = "{index} 번째 원소: {value}"
#for i, v in enumerate(arr):
#    print(tpl.format(index = i, value = v))

#for i, v in enumerate(arr):
#    print(f"{i} 번째 원소: {v}")
#---------------------------------------

array = [10 20 30 40 50]
배열의 원소의 갯수: 5
첫 번째 원소: 10
마지막 두개 원소: [40 50]
0 번째 원소: 10
1 번째 원소: 20
2 번째 원소: 30
3 번째 원소: 40
4 번째 원소: 50


### 02. ndarray의 주요 기능

In [29]:
# 문제의 주어진 점수데이터 조건:
score = [72.5, 88.0, 91.5, 67.0, 80.0, 59.5]

#-----------------------------------------------------
# numpy 라이브러리 import 해오기:
import numpy as np

#-----------------------------------------------------
# 위의 점수 리스트 -> 정수형 ndarray로 변환하기:
arr = np.array(score, dtype = 'int')
print("원본 점수:", arr)

#-----------------------------------------------------
# 그 중 80점 이상인 점수만 추출하기:
over80 = arr[arr >= 80]
print("80점 이상:", over80)

#-----------------------------------------------------
# 주어진 기준 조건으로 각 점수에 해당하는 학점 부여하기:
conditions = [
    (arr >= 90),
    (arr >= 80),
    (arr >= 70)
]

values = ['A', 'B', 'C']

result = np.select(conditions, values, default = 'F')
print("학점 결과:", result)

#-----------------------------------------------------

원본 점수: [72 88 91 67 80 59]
80점 이상: [88 91 80]
학점 결과: ['C' 'B' 'A' 'F' 'B' 'F']


### 03. 그 밖의 ndarray 형태

In [35]:
# numpy 라이브러리 import 해오기:
import numpy as np

#-------------------------------------------
# 평균: 75, 표준편차: 5인 3행 4열 랜덤점수 데이터 생성하기:
# (조건: 랜덤시드: 100으로 고정)
np.random.seed(100)
print(np.random.normal(75, 5, (3, 4))) # 튜플 형태로 행렬 표현
#print(np.random.normal(75, 5, [3, 4])) # 행렬을 표현할 때 리스트로 나타내도 됨
# np.random.rand(70, 80, (3, 4)) 는 에러 뜸!!

#-------------------------------------------
# 생성된 점수배열 중 80점 이상만 추출하기:
# (1차원 배열로 추출하기)
score = np.random.normal(75, 5, (3, 4))
result = score[score >= 80]
print("80점 이상 점수:", result)

#-------------------------------------------
# 생성한 점수배열의 차원, 형태, 데이터 타입 출력하기:
print("차원:", score.ndim)
print("형태:", score.shape)
print("데이터 타입:", score.dtype)


[[66.25117263 76.71340202 80.76517901 73.73781982]
 [79.90660393 77.57109421 76.10589835 69.64978335]
 [74.05252085 76.27500722 72.70986507 77.17581744]]
80점 이상 점수: [80.14866343 83.0949083  82.70802587]
차원: 2
형태: (3, 4)
데이터 타입: float64


### 04. ndarray의 형태 변환:  형변환, 차원변환

In [38]:
# 1. numpy 라이브러리 참조하기:
import numpy as np

#-------------------------------------
# 2. 0부터 11까지의 정수 배열 생성:
arr = np.arange(12)
#arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print("원본 배열:", arr)

#-------------------------------------
# 3. 생성한 배열의 데이터 타입을 실수로 바꾸기:
arr1 = np.asarray(arr, dtype='float')
#arr1 = arr.astype('float')
print("-> 실수형 변환:", arr1)

#-------------------------------------
# 4. 변환한 배열의 차원을 2행 6열로 바꾸기:
arr2 = arr1.reshape(2, 6)
print("-> 2행 6열로 변환:", arr2)

#-------------------------------------
# 5. 바꾼 배열을 '열 수에 관계 없이' '3행'으로 자동 변환되는 배열로 바꾸기
arr3 = arr2.reshape(3, -1)
print("-> 열 수에 관계없이 3행으로 자동 변환:", arr3)

#-------------------------------------
# 6. 1차원 배열로 축소시키기:
arr4 = arr3.reshape(-1)
print("-> 1차원으로 배열 축소:", arr4)

#-------------------------------------

원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]
-> 실수형 변환: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
-> 2행 6열로 변환: [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
-> 열 수에 관계없이 3행으로 자동 변환: [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
-> 1차원으로 배열 축소: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


### 05. 기초 통계량의 이해 (1)

In [25]:
import numpy as np

def data(b):
    myarr = np.array(b)
    n_b = len(myarr)           # 도수
    avg_b = np.average(myarr)        # 평균
    std_b = np.std(myarr)            # 표준편차
    min_b = np.min(myarr)            # 최솟값
    q1_b = np.quantile(myarr, 0.25) # 1사분위 수
    med_b = np.median(myarr)         # 중위값
    q3_b = np.quantile(myarr, 0.75) # 3사분위 수
    max_b = np.max(myarr)            # 최댓값
    
    print([n_b, avg_b, std_b, min_b, q1_b, med_b, q3_b, max_b])

In [26]:
Alphaa = [88, 92, 76, 100, 95, 81, 79, 98, 85, 87]
Bravoo = [65, 99, 78, 72, 80, 91, 75, 82, 89, 70]

b = Alphaa
data(Alphaa)

[10, np.float64(88.1), np.float64(7.7), np.int64(76), np.float64(82.0), np.float64(87.5), np.float64(94.25), np.int64(100)]


In [27]:
b = Bravoo
data(Bravoo)

[10, np.float64(80.1), np.float64(9.924212815130478), np.int64(65), np.float64(72.75), np.float64(79.0), np.float64(87.25), np.int64(99)]


In [28]:
[
    []
]

[[]]

### 06. 기초 통계량의 이해 (2)

In [93]:
# 2024년도 월별 교통사고 건 수
#-----------------------------------------------
# -> 1. 기초통계량 구하기:
import numpy as np

monthly_accident = [15129, 13836, 15738, 16300, 17605, 16690, 16252, 17000, 16956, 17720, 17455, 15668]
accdnt_arr = np.array(monthly_accident)
print(accdnt_arr)

arr_n = len(accdnt_arr)
arr_avg = np.average(accdnt_arr)
arr_std = np.std(accdnt_arr)
arr_min = np.min(accdnt_arr)
arr_q1 = np.quantile(accdnt_arr, 0.25)
arr_med = np.median(accdnt_arr)
arr_q3 = np.quantile(accdnt_arr, 0.75)
arr_max = np.max(accdnt_arr)
arr_var = np.var(accdnt_arr)

print("#-----------------------------------------------")
#-----------------------------------------------
print("1. 기초 통계량 구하기:")

# 데이터 범위 -> 전체 변동 폭
print("- 데이터 범위:", arr_max - arr_min)
print("- 평균:", arr_avg, ", 중앙값:", arr_med)

# IQR (Q3 - Q1) -> 중앙 50% 분포 폭, 이상치 판단
print("- 사분위 수 구간(IQR):", arr_q3 - arr_q1)

# 분산(변동성 크기) / 표준편차(평균으로부터의 거리, 안정성 척도)
print("- 분산:", arr_var, ", 표준편차:", arr_std)

print(" => 숫자가 너무 크기 때문에 표준화 ㄱㄱ~ 보기 어려웡~~")

print("#-----------------------------------------------")
#-----------------------------------------------
# 표준화: 평균=0, 표준편차=1로 통일
rand_arr = []
for i in accdnt_arr:
    z = round(((i - arr_avg) / arr_std), 2)
    rand_arr.append(z)
print("2. 데이터 표준화 (평균 0, 표준편차 1):", rand_arr)
#-----------------------------------------------
print("=> 표준화 했으니 이젠 도수분포표 개념 써서 분포도 함 만들어봐야겠다눙!")

print("#-----------------------------------------------")
#-----------------------------------------------

[15129 13836 15738 16300 17605 16690 16252 17000 16956 17720 17455 15668]
#-----------------------------------------------
1. 기초 통계량 구하기:
- 데이터 범위: 3884
- 평균: 16362.416666666666 , 중앙값: 16495.0
- 사분위 수 구간(IQR): 1393.25
- 분산: 1186603.7430555557 , 표준편차: 1089.3134273732037
 => 숫자가 너무 크기 때문에 표준화 ㄱㄱ~ 보기 어려웡~~
#-----------------------------------------------
2. 데이터 표준화 (평균 0, 표준편차 1): [np.float64(-1.13), np.float64(-2.32), np.float64(-0.57), np.float64(-0.06), np.float64(1.14), np.float64(0.3), np.float64(-0.1), np.float64(0.59), np.float64(0.54), np.float64(1.25), np.float64(1.0), np.float64(-0.64)]
=> 표준화 했으니 이젠 도수분포표 개념 써서 분포도 함 만들어봐야겠다눙!
#-----------------------------------------------


In [ ]:
rand_arr = np.array(
    [-1.13, -2.32, -0.57, -0.86, 1.14, 0.3, -0.1, 0.59, 0.54, 1.25, 1.0, -0.64]
)
rand_arr

array([-1.13, -2.32, -0.57, -0.86,  1.14,  0.3 , -0.1 ,  0.59,  0.54,
        1.25,  1.  , -0.64])

In [94]:
print("#-----------------------------------------------")
print("3-1. 표준화 데이터 구간:", np.max(rand_arr) - np.min(rand_arr))
print("3-2. 표준화 데이터 평균:", np.average(rand_arr))
print("3-3. 표준화 데이터 중앙값:", np.median(rand_arr))
print("3-4. 표준화 데이터 IQR:", np.quantile(rand_arr, 0.75) - np.quantile(rand_arr, 0.25))
print("3-5. 표준화 데이터 분산:", np.var(rand_arr))
print("3-6. 표준화 데이터 표준편차:", np.std(rand_arr))
print("#-----------------------------------------------")
print("결론1: 표준화한 평균과 중앙값이 0에 근접하지만 월별 교통사고 건 수 편차가 심하다.")
print("결론2: IQR/구간(%) =", (np.quantile(rand_arr, 0.75) - np.quantile(rand_arr, 0.25)) / (np.max(rand_arr) - np.min(rand_arr)) * 100, "=> IQR이 작다는건 중앙에 데이터가 포진 해 있지 않다는 뜻")
print("결론3: IQR(%)와 표준편차의 해석 결과, 24년도 월별 교통사고 건 수 데이터가 실제로 어떤 그래프 모양을 띄는지 볼 필요가 있다 => 도수분포표 ㄱㄱ")
print("#-----------------------------------------------")

#-----------------------------------------------
3-1. 표준화 데이터 구간: 3.57
3-2. 표준화 데이터 평균: -2.7755575615628914e-17
3-3. 표준화 데이터 중앙값: 0.12
3-4. 표준화 데이터 IQR: 1.2799999999999998
3-5. 표준화 데이터 분산: 0.9999333333333332
3-6. 표준화 데이터 표준편차: 0.9999666661110925
#-----------------------------------------------
결론1: 표준화한 평균과 중앙값이 0에 근접하지만 월별 교통사고 건 수 편차가 심하다.
결론2: IQR/구간(%) = 35.85434173669467 => IQR이 작다는건 중앙에 데이터가 포진 해 있지 않다는 뜻
결론3: IQR(%)와 표준편차의 해석 결과, 24년도 월별 교통사고 건 수 데이터가 실제로 어떤 그래프 모양을 띄는지 볼 필요가 있다 => 도수분포표 ㄱㄱ
#-----------------------------------------------


In [95]:
rand_arr = np.array(
    [-1.13, -2.32, -0.57, -0.86, 1.14, 0.3, -0.1, 0.59, 0.54, 1.25, 1.0, -0.64]
)
rand_arr
print("#-----------------------------------------------")
print("4. 표준화 한 데이터가 어떤 모양을 가지는지 도수분포표로 대략적으로 함 보자!")

hist, bins = np.histogram(rand_arr, [-3, -2, -1, 0, 1, 2, 3, 4])
print("- 표준화 된 구간 별 데이터 수:", hist)
print("- 구간 경계:", bins)
print("#-----------------------------------------------")

#-----------------------------------------------
4. 표준화 한 데이터가 어떤 모양을 가지는지 도수분포표로 대략적으로 함 보자!
- 표준화 된 구간 별 데이터 수: [1 1 4 3 3 0 0]
- 구간 경계: [-3 -2 -1  0  1  2  3  4]
#-----------------------------------------------


In [96]:
from pandas import DataFrame

z_range = list(bins)
z_values = list(hist)
z_data = [bins, hist]

#print(z_range)
#print(z_values)
#z_data
print("#-----------------------------------------------")
print("5. ↓: 1번째 행은 표준화된 데이터의 표준편차 구간,")
print("2번째 행은 각 구간 별 데이터 갯수")
df = DataFrame(z_data)
df

#-----------------------------------------------
5. ↓: 1번째 행은 표준화된 데이터의 표준편차 구간,
2번째 행은 각 구간 별 데이터 갯수


0  1  2  3  4  5  6    7
0 -3 -2 -1  0  1  2  3  4.0
1  1  1  4  3  3  0  0  NaN

In [97]:
print("#-----------------------------------------------")
print("6. 최종 결론: 월 평균 교통사고 건 수 보다 낮은 달이 없진 않지만, 평균보다 교통사고 건수가 높은 달이 더 많음 -> 다른 독립변수 존재의 가능성이 보임.")
print("-> 결론으로 인한 앞으로의 목표: 추가 독립변수가 어떤 것들이 있는지 추가 EDA 필요")
print("#-----------------------------------------------")

#-----------------------------------------------
6. 최종 결론: 월 평균 교통사고 건 수 보다 낮은 달이 없진 않지만, 평균보다 교통사고 건수가 높은 달이 더 많음 -> 다른 독립변수 존재의 가능성이 보임.
-> 결론으로 인한 앞으로의 목표: 추가 독립변수가 어떤 것들이 있는지 추가 EDA 필요
#-----------------------------------------------
